### ISSUE TITLE
UnicodeEncodeError on build

### ISSUE THREAD

**Issue by danmash** [scrapinghub/shub-image#22]
Hi, I get following error.

Step 14 : RUN wget https://github.com/danmash/pdfminer/archive/master.zip     && unzip master.zip && cd pdfminer-master && python setup.py install                                          
 ---> Running in 4bb4a6a37d54                                                                                                                                                               
--2016-11-26 09:11:01--  https://github.com/danmash/pdfminer/archive/master.zip                                                                                                             
Resolving github.com (github.com)...                                                                                                                                                        
192.30.253.113, 192.30.253.112                                                                                                                                                              
Connecting to github.com (github.com)|192.30.253.113|:443... 
connected.

HTTP request sent, awaiting response... 
302 Found
Location: https://codeload.github.com/danmash/pdfminer/zip/master [following]

--2016-11-26 09:11:02--  https://codeload.github.com/danmash/pdfminer/zip/master
Resolving codeload.github.com (codeload.github.com)... 
192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... 
connected.

HTTP request sent, awaiting response... 
200 OK
Length: 4199594
 (4.0M) [application/zip]
Saving to: ‘master.zip’

raceback (most recent call last):
  File "/usr/local/bin/shub-image", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/shub_image/build.py", line 37, in cli
    build_cmd(target, version)
  File "/usr/local/lib/python2.7/dist-packages/shub_image/build.py", line 55, in build_cmd
    utils.debug_log("{}".format(data['stream'][:-1]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 42: ordinal not in range(128)

**Comment by vshlapakov** [comment]
@danmash Hi, the project was deprecated half year ago, please switch to [shub](https://pypi.python.org/pypi/shub/2.7.0) (start with [this section](https://shub.readthedocs.io/en/stable/deploy-custom-image.html)).
